name: buzzwatch_env_back
channels:
  - conda-forge
  - defaults  # Default channel for general packages
dependencies:
  - python=3.8
  - numpy=1.23.5
  - scipy=1.10.1
  - matplotlib=3.7.2
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - opencv  # OpenCV package via Conda
  - pillow=9.5.0
  - pytz=2023.3
  - pyyaml=6.0
  - cython=0.29.36
  - llvmlite=0.39.1
  - numba=0.56.4
  - h5py=3.8.0
  - cloudpickle  # Used by moviepy
  - pip  # Ensure pip is available in the environment
  - pip:
      - altgraph==0.17.4
      - babel==2.16.0
      - brotli==1.0.9
      - certifi==2023.5.7
      - chardet==5.2.0
      - charset-normalizer==3.1.0
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.11.0
      - decorator==4.4.2
      - et-xmlfile==1.1.0
      - fonttools==4.38.0
      - idna==3.4
      - imageio==2.31.0
      - imageio-ffmpeg==0.4.9
      - importlib-resources==6.1.0
      - joblib==1.3.1
      - kiwisolver==1.4.4
      - macholib==1.16.2
      - moviepy==1.0.3
      - munkres==1.1.2
      - openpyxl==3.0.9
      - packaging==23.2
      - patsy==0.5.3
      - platformdirs==3.11.0
      - pooch==1.8.1
      - proglog==0.1.10
      - pyinstaller==5.12.0
      - pyinstaller-hooks-contrib==2023.10
      - pynndescent==0.5.9
      - pyparsing==3.0.9
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - requests==2.31.0
      - seaborn==0.11.2
      - six==1.16.0
      - statsmodels==0.14.0
      - threadpoolctl==3.1.0
      - tkcalendar==1.5.0
      - tornado==6.3
      - tqdm==4.65.0
      - typing_extensions==4.8.0
      - tzdata==2023.3
      - umap-learn==0.5.3
      - unicodedata2==15.0.0
      - urllib3==1.26.16
      - zipp==3.15.0