name: buzzwatch_env
channels:
  - conda-forge
dependencies:
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.20.1
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cairo=1.16.0
  - certifi=2024.2.2
  - charset-normalizer=3.3.1
  - colorama=0.4.6
  - contourpy=1.1.1
  - cycler=0.12.1
  - cython=3.0.9
  - ffmpeg=4.3.2
  - fontconfig=2.13.94
  - fonttools=4.43.1
  - freetype=2.12.1
  - gettext=0.21.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.13
  - h5py=3.6.0
  - harfbuzz=3.0.0
  - hdbscan=0.8.33
  - hdf5=1.12.1
  - icu=68.2
  - idna=3.4
  - importlib-metadata=7.0.2
  - importlib-resources=6.1.0
  - jasper=2.0.33
  - joblib=1.3.2
  - jpeg=9e
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.14
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.68.4
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.51.0
  - libopenblas=0.3.24
  - libopencv=4.5.3
  - libpng=1.6.39
  - libprotobuf=3.18.3
  - libsqlite=3.43.2
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxml2=2.9.12
  - libzlib=1.2.13
  - llvmlite=0.40.1
  - matplotlib=3.7.3
  - matplotlib-base=3.7.3
  - munkres=1.1.4
  - ncurses=6.4
  - nettle=3.6
  - numba=0.57.1
  - numpy=1.24.4
  - opencv=4.5.3
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=1.1.1w
  - packaging=23.2
  - pandas=2.0.3
  - pcre=8.45
  - pip=23.3.1
  - pixman=0.42.2
  - platformdirs=3.11.0
  - pooch=1.8.0
  - pthread-stubs=0.4
  - py-opencv=4.5.3
  - pynndescent=0.5.11
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.8.*
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.8
  - pytz=2023.3.post1
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.43.2
  - tbb=2021.10.0
  - threadpoolctl=3.3.0
  - tk=8.6.13
  - tornado=6.3.3
  - tqdm=4.66.2
  - typing-extensions=4.8.0
  - umap-learn=0.5.5
  - unicodedata2=15.1.0
  - urllib3=2.0.7
  - wheel=0.41.2
  - x264=1!161.3030
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - altgraph==0.17.4
      - babel==2.16.0
      - chardet==5.2.0
      - decorator==4.4.2
      - et-xmlfile==1.1.0
      - imageio==2.34.1
      - imageio-ffmpeg==0.4.9
      - macholib==1.16.3
      - moviepy==1.0.3
      - opencv-python==4.10.0.84
      - openpyxl==3.1.2
      - pillow==10.4.0
      - proglog==0.1.10
      - pyinstaller==6.10.0
      - pyinstaller-hooks-contrib==2024.8
      - pyyaml==6.0.1
      - seaborn==0.13.2
      - tkcalendar==1.6.1